import type { QrRow } from "./QrTable";

/**
 * Placeholder rows, carried over from the designer's dashboard.
 *
 * Created codes are not persisted yet — there is no table for them and no
 * hosted destination behind the dynamic types — so the list renders this fixed
 * set. Swap it for a query the moment saving lands; nothing else here changes.
 */
export const sampleRows: QrRow[] = [
  {
    id: "1",
    name: "My Website QR Code",
    description: "Scan to visit our website",
    link: "www.mywebsite.com",
    createdDate: "Aug 19, 2024",
    createdTime: "10:24 AM",
    passwordOn: false,
    status: "Active",
    health: "Healthy",
    type: "website",
    scans: null,
    thumbnail: "/dashboard/qr-01.svg",
    isNew: true,
  },
  {
    id: "2",
    name: "Brad Social Media",
    description: "Add a description...",
    link: "www.instagram.com/brad",
    createdDate: "Aug 17, 2024",
    createdTime: "3:15 PM",
    passwordOn: true,
    status: "Active",
    health: "Healthy",
    type: "social",
    scans: 3,
    thumbnail: "/dashboard/qr-02.svg",
  },
  {
    id: "3",
    name: "TPA Location QR",
    description: "Add a description...",
    link: "www.google.com/maps/place/TPA",
    createdDate: "Aug 17, 2024",
    createdTime: "11:02 AM",
    passwordOn: false,
    status: "Active",
    health: "Healthy",
    type: "location",
    scans: 1,
    thumbnail: "/dashboard/qr-03.svg",
  },
  {
    id: "4",
    name: "vCard QR Code",
    description: "Add a description...",
    link: "www.mycontact.com/vcard",
    createdDate: "Aug 17, 2024",
    createdTime: "9:47 AM",
    passwordOn: false,
    status: "Active",
    health: "Healthy",
    type: "vcard",
    scans: 2,
    thumbnail: "/dashboard/qr-04.svg",
  },
  {
    id: "5",
    name: "Website QR Code",
    description: "Add a description...",
    link: "www.pubix.com",
    createdDate: "Aug 17, 2024",
    createdTime: "9:05 AM",
    passwordOn: false,
    status: "Active",
    health: "Healthy",
    type: "website",
    scans: 1,
    thumbnail: "/dashboard/qr-01.svg",
  },
  {
    id: "6",
    name: "My Website 2",
    description: "Add a description...",
    link: "www.google.com",
    createdDate: "Aug 11, 2024",
    createdTime: "2:28 PM",
    passwordOn: false,
    status: "Active",
    health: "Healthy",
    type: "website",
    scans: 7,
    thumbnail: "/dashboard/qr-05.svg",
  },
];
